-- -----------------------------------------------------
-- Schema full-stack-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `full-stack-ecommerce`;

CREATE SCHEMA `full-stack-ecommerce`;
USE `full-stack-ecommerce` ;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(2000) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO product_category(category_name) VALUES ('Red Wine');
INSERT INTO product_category(category_name) VALUES ('White Wine');
INSERT INTO product_category(category_name) VALUES ('Rosé ');
INSERT INTO product_category(category_name) VALUES ('Sparkling Wine');

-- -----------------------------------------------------
-- Red Wine
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('RED-WINE-1000', '360° Loire Cabernet Franc Val de Loire IGP 2020', 'Aromas of fresh red fruits (strawberries, blackberries) with floral nuances. Supple and elegant tannins, medium body. Will match perfectly with you salads, picnics, poultry, delicatessen or cheeses.', 'assets/images/products/redwine/redwine-1.jpeg', 1, 100, 37.00, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('RED-WINE-1000', 'Alois Lageder Cason Rosso 2018 *Bio', 'Colour: Cherry-red with a pink shimmer Nose: Slightly aromatic, fruity (plum, blackberry), leather, tea and woody Palate: Medium bodied, juicy, fruity, refined bitter, fresh and lively', 'assets/images/products/redwine/redwine-2.jpeg', 1, 100, 99.00, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('RED-WINE-1000', 'Alois Lageder Conus Lagrein 2019 *Bio', 'Colour: Cherry red with a ruby shimmer Nose: Quite aromatic, fruity (plum), licorice notes, cacao, spicy, floral Palate: Full bodied, intense, linear, well-balanced, silky and well integrated tannins', 'assets/images/products/redwine/redwine-3.jpeg', 1, 100, 60, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('RED-WINE-1000', 'Altos Las Hormigas Malbec Classico 2020', 'This is a Malbec with an intense ruby red color, showing deep violet hues. It is very expressive on the nose, presenting notes of red fruits, plums, cherries and raspberries. It also has subtle aromas of orange rinds and “jarilla”, a typical plant from Mendoza. The entry in the palate is very fresh, with a soft acidity that travels through the mouth. It is a concentrated, juicy and very balanced wine, with a long and pleasant finish. It is ideal to pair with various dishes, from red meats to pasta or grilled vegetables', 'assets/images/products/redwine/redwine-4.jpeg', 1, 100, 45.00, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('RED-WINE-1000', 'Babich Marlborough Pinot Noir 2021', 'Mushroom and Morello cherry mingle with almond and strawberry aromas. Dried herbs add complexity to the sweet notes. Sweet dark fruits and raspberry follow on from a smooth even entry. The fresh fruits are layered with vanilla and forest floor complexity while the very fine tannins fade into a pleasing cocoa on the spicy finish.', 'assets/images/products/redwine/redwine-5.jpeg', 1, 100, 51.00, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('RED-WINE-1000', 'Bertinga Sassi Chiusi IGT Toscana Rosso 2017', 'Colour: ruby red, brilliant reflections. Nose: very expressive, notes of exotic fruit, vine peaches and dried apricots, floral notes of orange blossoms and pink peppercorns. Taste: the attack is frank and dynamic, the tannic frame is fine and tight. It is soft and sapid. The finish is saline and refreshing.', 'assets/images/products/redwine/redwine-6.jpeg', 1, 100, 54.00, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('RED-WINE-1000', 'Bodega Cerrón El Tiempo Que Nos Une 2019', 'The wine has a Mediterranean character with power, finesse and fluidity. The load of red fruit and scrub flowers is important and can be drunk now or stored for a few years.', 'assets/images/products/redwine/redwine-7.jpeg', 1, 100, 38.00, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('RED-WINE-1000', 'Braida Ai Suma Barbera d’Asti 2019', 'Very deep ruby red colour with garnet highlights. Ample, rich and complex bouquet with numerous scents of fruit and a background of vanilla, liquorice and cocoa notes. Full, powerful flavour with a great structure, yet elegant and sensual at the same time, harmonious and very persistent. Ideal with roasts and meat dishes, also with sauces, and mature cheeses.', 'assets/images/products/redwine/redwine-8.jpeg', 1, 100, 173.00, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('RED-WINE-1000', 'Braida Brachetto D’Acqui 2020', 'Light ruby red colour with purple highlights, lively froth and persistent perlage. Vigorous, fragrant and aromatic perfume with evident scents of ripe red fruit and withered Rosé. Sweet, smooth, delicate, sparkling and suave with a lingering aromatic persistence. It pairs with strawberries, forest fruits and with dried fruit too, such as walnuts, hazelnuts, almonds, pistachios and figs. The most traditional pairing, with dessert at the end of a meal or in the middle of the afternoon, is with pastries and cakes, from Christmas panettone to jam tart. Braida Brachetto d’Acqui is perhaps the only wine in the world which is the perfect match for chocolate.', 'assets/images/products/redwine/redwine-9.jpeg', 1, 100, 52.00, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('RED-WINE-1000', 'Braida Bricco Della Bigotta Barbera d’Asti 2017', 'Ruby-garnet red color with purplish highlights. A rich, intense and persistent perfume, well-evolved, with sensations of liquorice, violet, plum and vanilla. Fruit and spice emerge on the palate, with flavors ranging from roast coffee to stronger yet nicely balanced spices, vigorous and intense. Its rich expression is due to the spices that envelop the flavor of ripe plum (the most evident fruit), conveying a suave and potent touch. Ideal with roast meat, game and hard cheeses', 'assets/images/products/redwine/redwine-10.jpeg', 1, 100, 141.00, 1, NOW());

-- -----------------------------------------------------
-- White Wine 
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', '360° Loire Chenin Blanc Val de Loire IGP 2020', '100% chenin blanc from Loire Valley. Aromas of apricot, lime, honey and acacia flowers. Supple and smooth attack. Will match perfectly with your shellfish, seafood, grilled fish, white meats or cheeses.', 'assets/images/products/whitewine/whitewine-1.jpeg', 1, 100, 37.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Alois Lageder Chardonnay 2021', 'Colour: Brillant, clear, straw-yellow with a green hint Nose: Delicate aroma, pronounced bouquet, fresh, fruity(peach, melone, citrus), floral and mineral Palate: Medium bodied, well-balanced, fruity, juicy and dry', 'assets/images/products/whitewine/whitewine-2.jpeg', 1, 100, 52.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Alois Lageder Forra Manzoni Bianco 2020 *Bio', 'Colour: Clear, intense gold-yellow Nose: Slightly aromatic, pronounced, fruity (quince, pear) flintstone, spicy Palate: Full bodied, concentrated, quite rich, fresh, spicy, dry', 'assets/images/products/whitewine/whitewine-3.jpeg', 1, 100, 70.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Alois Lageder Löwengang Chardonnay 2019', 'Colour: Clear, gold-yellow Nose: Pronounced and intense nose, fruity (pear, apricot, peach) fresh butter, woody Palate: Full bodied, multi-layered, mineral, fruity and salty', 'assets/images/products/whitewine/whitewine-4.jpeg', 1, 100, 114.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Alois Lageder Müller Thurgau 2021 *Organic', 'Colour: Brillant, clear, bright straw-yellow with a green shimmer Aroma: Semi-aromatic, youthful, fruity (apricotes, apples), floral, nutmeg Palate: Light bodied, elegant, structured, lively fresh, dry', 'assets/images/products/whitewine/whitewine-5.jpeg', 1, 100, 51.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Alpha Box & Dice Ö Grüner Veltliner 2021', 'Nose: White stone fruit, marzipan, quince. Palate: Bursting with delicious fruit that resolves into a generous level of texture balanced by a cleansing acidity. Pairing: Chicken caesar salad, creamy pesto pasta.', 'assets/images/products/whitewine/whitewine-6.jpeg', 1, 100, 62.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Alpha Box & Dice Very Special Riesling 2022', 'Aroma: White flowers, citrus zest and crabapples. Palate: It bursts with generous flavour immediately that tightens towards a linear finish, with structure and acidity intertwined in a sweet, harmonious embrace.', 'assets/images/products/whitewine/whitewine-7.jpeg', 1, 100, 44.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Azulejo Vinho Regional Lisboa White 2021', 'This is a very aromatic and fruity wine. On the nose, citric notes stand out, which the palate shows once again revealing also a lively wine with, balanced acidity and great freshness.', 'assets/images/products/whitewine/whitewine-8.jpeg', 1, 100, 35.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Babich Headwaters Organic Sauvignon Blanc 2022', 'Sweet lime, slate and gooseberry notes and a light spice aroma. Lemon and apple flavours supported by mineral and spice notes. Good depth, texture and length. Fleshy with great drive.', 'assets/images/products/whitewine/whitewine-9.jpeg', 1, 100, 51.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Big Max Chardonnay 2018', 'Color: Pale yellow with golden hues Aroma: Green apple and honeysuckle aromas are closely followed by pretty stone fruit, white peach and apricot, with just the right touch of soft, toasty vanilla. Taste: Medium-bodied entry spreads out on the palate with crisp fruit and toasty flavors, vibrant, salivating acidity and a long finish', 'assets/images/products/whitewine/whitewine-10.jpeg', 1, 100, 69.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Brokenwood Sémillon 2020', 'Vibrant in colour – a touch more than usual due to the warm year. Lovely florals and lemon grass aromas. Mouth filling flavours of pear and lemon pith balancing the zesty acid backbone. Slightly richer in style than the previous years, a classic Hunter Valley Semillon to enjoy now or age gracefully.', 'assets/images/products/whitewine/whitewine-11.jpeg', 1, 100, 49.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Can Sumoi Perfum 2021', 'Appearance: The white wine Can Sumoi Perfum is medium straw with some steely reflections. Nose: Quite expressive, this blend of Malvasía, Moscatel de Grano Menudo, Macabeo and Parellada carries aromas of flowers, juicy white fruit – notably white peaches and pressed grapes – over a subtle background of aromatic herbs. Palate: Savoury and elegant, the of this young white wine of Can Sumoi is fruit-driven and nicely balanced. Besides the fruit and the herbs, there are some interesting suggestions of salt and honey that end in a yummy, fresh finish.', 'assets/images/products/whitewine/whitewine-12.jpeg', 1, 100, 44.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Casa Marin Cartagena Sauvignon Blanc 2019', 'Pale straw in colour. On the nose, bright, fresh and lifted with distinctive melon, kiwi and grassy notes. Clean and beautifully structured with hints of citrus and honey and fine balanced acidity.', 'assets/images/products/whitewine/whitewine-13.jpeg', 1, 100, 47.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Château D’Yquem 2006', 'Medium bright yellow. Wonderfully fresh aromas of pineapple, coconut, caramel, vanilla and spices lifted by a floral element. Silky on entry, then dense but almost magically light on its feet, thanks to penetrating acidity that gives sharp definition to the tight, impressively concentrated lemon, pineapple and coconut flavors.', 'assets/images/products/whitewine/whitewine-14.jpeg', 1, 100, 988.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Château de Meursault Bourgogne Clos du Château Blanc 2020', 'Golden yellow colour. Gourmet on yellow fruits and spices. On yellow fruits, nice balance, spicy and toasted touches on the finish.', 'assets/images/products/whitewine/whitewine-15.jpeg', 1, 100, 101.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Château de Tracy Pouilly Fume 2021', 'Straw yellow with light greenish reflections, the nose expresses an unmistakable olfactory profile: mango, grapefruit, elderberry, vanilla, floral hints are just some of the notes that are the heritage of the great sauvignons. In the mouth it’s fresh, rich, almost creamy, characterized by a vehement acidity and an enviable balance. It closes with a finish that returns to citrus scents, of excellent persistence.', 'assets/images/products/whitewine/whitewine-16.jpeg', 1, 100, 76.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Château Gantonnet Bordeaux Blanc 2021', 'The color is bright pale yellow. The nose is expressed on aromas of white citrus flowers and white fruits. The palate is ample, fresh and with a persistent length. It is greedy with rich notes of white fruits and exotic fruits.', 'assets/images/products/whitewine/whitewine-17.jpeg', 1, 100, 39.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Château Kefraya Blanc de Blancs 2019', 'Rich and luscious, expressing fruit notes (pineapple, peach and grapefruit), as well as floral fragrances (lilies and white acacia). On the palate, this wine demonstrates great elegance, smoothness and liveliness, leaving an impression of fullness and roundness. The flavors on the palate complement those on the nose, with touches of apricot, mango and honey achieving great harmony. The finish is generous and long, rounding out the palate with slight herbal notes.', 'assets/images/products/whitewine/whitewine-18.jpeg', 1, 100, 47.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Château La Nerthe Clos Du Beauvenir 2013', 'The color is straw yellow with gray reflections. The nose is very expressive, very exuberant. There are floral notes of yellow flesh fruits (vine peach) but also some exotic notes (mangoes, pineapple). The bouquet gives a real impression of maturity and wealth. The mouth contrasts with the nose. The wine reveals itself there fresh, balanced, long. The power is there too but remains very contained, pledge of very good aging. The finish is juicy, saline on some notes toasted (almonds) and ripe fruit (pineapple, melon) with an endless feeling of elegance.', 'assets/images/products/whitewine/whitewine-19.jpeg', 1, 100, 245.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Clos Du Moulin Aux Moines Auxey-Duresses Monopole Blanc 2020', 'Clear, crystalline straw colour, in tune with its aromas of fresh almonds and pippin apple. Pretty biscuit nuances, mineral scents (flint) add to its bouquet. On the palate, it thistles well and greedily. Lively in its youth, it then develops its substance and fatness. Good aromatic persistence.', 'assets/images/products/whitewine/whitewine-20.jpeg', 1, 100, 104.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Côté Mas Sauvignon Vermentino 2020', 'The wine appears medium lemon with intense stone fruit character, enhanced by some green fruit and notes of citrus on the nose. The palate is vibrant with succulent peach and pear, clean and fresh, finishing balanced with hints of grapefruit and some underlying lime. Best served with fish and chicken dishes and consume young within 2-3 years.', 'assets/images/products/whitewine/whitewine-21.jpeg', 1, 100, 37.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Craven Chardonnay 2020', 'Mick and Jeanine Craven started Craven in 2014, with a focus on single vineyard wines sourced from growers to committed to organics. Aged in large format, old oak barrels, their Chardonnay strikes the perfect balance between texture and freshness', 'assets/images/products/whitewine/whitewine-22.jpeg', 1, 100, 53.00, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('WHITE-WINE-1000', 'Craven Chenin Blanc Karibib Vineyard 2020', 'Dried yellow peaches with a savoury note and fresh herbal touch. Mouth watering acidity on the finish. Suggest you keep this one for a while to give all the magic time to develop.', 'assets/images/products/whitewine/whitewine-23.jpeg', 1, 100, 53.00, 2, NOW());


-- -----------------------------------------------------
-- Rosé
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROSÉ-1000', '360° Loire Rosé Val de Loire IGP 2020', 'With its fruity and intense aromas of small red fruits, its beautiful vivacity and smoothness, this wine will match perfectly with exotic dishes or any desserts (fruits, chocolate, cheesecakes).', 'assets/images/products/roséwine/rosewine-1.jpeg', 1, 100, 38.00, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROSÉ-1001', 'Aix Rosé 2021', 'A pure, pale salmon pink coloured wine with gentle onion skin hues that shine from the glass upon swirling. A fine, delicate nose with floral blossom, peach, fresh citrus, and hints of red fruit lead to a classic fresh and bright palate, a spritely acidity balanced with wild strawberry, raspberry, and stone fruit notes. The 2021 vintage has a lovely line and tension driven by a wellintegrated acidity and crushed shell minerality, all leading to a surprisingly long and complex finish.', 'assets/images/products/roséwine/rosewine-2.jpeg', 1, 100, 52.00, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROSÉ-1002', 'Château Kefraya Myst 2019', 'This Myst rose is very Provencal in style: delicate and complex, it offers subtle floral notes on the nose and a palate of strawberries and red and black currants.', 'assets/images/products/roséwine/rosewine-3.jpeg', 1, 100, 48.00, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROSÉ-1003', 'Francesco Cirelli Cerasuolo d’Abruzzo Anfora 2019', 'With a strong cherry pink colour, the bouquet releases inviting aromas of cherry, pomegranate, orange peel, strawberry jam, with deep spicy and smoked scents. Juicy, fresh and very savoury, the palate is continually intrigued, exhorting you to drink it with its excellent balance between softness and acidity', 'assets/images/products/roséwine/rosewine-4.jpeg', 1, 100, 73.00, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROSÉ-1004', 'Gut Oggau Cecilia 2021', 'If a seriously satisfying Rose that’s a little bit different is something you’re looking for, let us introduce you to Cecilia! This is the newest addition to the Gut Oggau family – a gemischter satz (field blend) of red and white varieties from a little plot that was brought back to life by Steffi and Edouard. The grapes are hand picked, then a portion is pressed while the rest are crushed and macerated for a short time. It then sits in large format barrels to mature. What emerges is a beautifully bright, crunchy and lively Rose made in a deliciously dry style. Sure to pair well with just about everything.', 'assets/images/products/roséwine/rosewine-5.jpeg', 1, 100, 108.00, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROSÉ-1005', 'Marqués de Murrieta Rosé 2021', 'Its subtle nose is the perfect wrapper for a wine with a solid palate. Fresh aromas of raspberries, blood orange, lavender and pink pepper. Freshness and liveliness on the palate combine with a persistent and expressive finish. Delicate, fluid and flavorful.', 'assets/images/products/roséwine/rosewine-6.jpeg', 1, 100, 94.00, 3, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('ROSÉ-1006', 'Pasqua 11 Minutes Rosé Trevenezie 2022', 'The Corvina varietal dominates in terms of percentage and was chosen because it is one of the principal cultivars in our territory and for the floral aroma it gives the wine as well as guaranteeing significant acidity. Trebbiano brings elegance and a long aftertaste; Syrah gived fine fruit and spice notes to the glass and finally, Carmenre creates structure, ensuring stability over time. Due to the dark nature of the grape skins, only 11 minutes of skin contact is required to impart the beautiful pink colour.', 'assets/images/products/roséwine/rosewine-7.jpeg', 1, 100, 48.00, 3, NOW());


-- -----------------------------------------------------
-- Sparkling Wine
-- -----------------------------------------------------
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPARKLING-WINE-1000', 'Alpha Box & Dice Tarot Prosecco NV', 'Apple blossom, lychees and a hint of honey. Palate: Zippy and fresh acid drives the palate, with a soft mousse that works beautifully with the generous mouthfeel. Pairing: Sunshine, oysters, sashimi and hard cheeses.', 'assets/images/products/sparklingwine/sparklingwine-1.jpeg', 1, 100, 49.00, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPARKLING-WINE-1001', 'Champagne Deutz Blanc De Blancs Vintage 2017', 'Harmonious and lively at the same time, the Deutz Blanc de Blancs Millésimé cuvée expresses all its poetry in the reflections of its light color, a heritage of Chardonnay. The wine is perfectly chiseled as evidenced by the finesse and minerality of its nose; then the tones of verbena, ripe white fruit and dried white flowers.', 'assets/images/products/sparklingwine/sparklingwine-2.jpeg', 1, 100, 172.00, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPARKLING-WINE-1002', 'Champagne Deutz Brut Classic NV', 'The most eclectic of the range, Deutz Brut Classic draws its perfect harmony from the three Champagne grape varieties: Chardonnay, Pinot Noir and Pinot Meunier, which gives it its perfect balance. The golden color reveals a graceful ballet of bubbles of great finesse. Very expressive, the cuvée reveals sweet floral notes supported by aromas of toast, marzipan and ripe fruit. Its silky texture bears witness to a fine balance between the freshness of Chardonnay, the fruitiness of Pinot Noir and the touch of vinosity of Pinot Meunier.', 'assets/images/products/sparklingwine/sparklingwine-3.jpeg', 1, 100, 109.00, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPARKLING-WINE-1003', 'Champagne Deutz Brut Rose Vintage 2014', 'Deutz Rosé Vintage bewitches. Its finery, of an adorably coppery pink asserts the elegance of this seductive Champagne. Expressive, the nose reveals all the power of the Pinot Noir picked at the height of its maturity. Invaded by floral and gourmet notes from a basket of red fruits, the mouth is sustained. The flesh is compact, the texture is silky; the dream continues…', 'assets/images/products/sparklingwine/sparklingwine-4.jpeg', 1, 100, 138.00, 4, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPARKLING-WINE-1004', 'Champagne Drappier Brut Nature Rosé', 'On the nose, very evocative of strawberry and raspberry with a floral note of Rosé petals. The palate recalls red fruits and is augmented by hints of citrus fruit, mandarin orange and a small, very refined touch of white pepper.', 'assets/images/products/sparklingwine/sparklingwine-5.jpeg', 1, 100, 110.00, 4, NOW());
